language: java

before_install:
  - sudo apt-get install ant
  - export CLASSPATH=/usr/share/java/junit4-4.12.jar
  - whereis java

jdk:
  - openjdk8

install: ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - jbustamante@fi.uba.ar
    on_failure: always
